[package]
name = "git-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = []
app-store = ["dep:ssh2"]

[dependencies]
git2 = { workspace = true }
notify = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt"] }

serde = { workspace = true }
serde_json = { workspace = true }
dirs-next = { workspace = true }
similar = "3.0.0"
reqwest = { workspace = true }

tempfile = { workspace = true }
fs2 = "0.4.3"
ssh2 = { version = "0.9.6", optional = true }
